### ISSUE TITLE
Support oauth2 security specification

### ISSUE THREAD

**Issue by MDUYN** [coding-kitties/flask-swagger-generator#37]
A specification similar to this:

```
securitySchemes:
  oauth:
    type: oauth2
    description:
    flows:
      implicit:
        authorizationUrl: ""
        tokenUrl: ""
        scopes:
          openid: Read user information
          "" : Application Scope
    x-tokenInfoFunc: controllers.authorization_controller.check_oAuth2AuthCode
    x-scopeValidateFunc: controllers.authorization_controller.validate_scope_oAuth2AuthCode
```
